### ISSUE TITLE
关于php artisan key:generate

### ISSUE THREAD

**Issue by chinaLovinger** [Kuri-su/Portflow-Monitor#1]
PHP Parse error:  syntax error, unexpected '?' in /masterNode/app/Console/Kernel.php on line 33

**Comment by Kuri-su** [comment]
抱歉比较久才看到，估计是 `PHP` 版本的问题，因为??的写法是 `php7` 才开始支持
最好的解决方法当然是安装 `php7`
如果因为某些原因无法更新 `php7` 的话，可以考虑把 ` /masterNode/app/Console/Kernel.php` 的第 `33`行改成这样
```php
 $sendMail = new MainController( config( 'mail.childNode.ip' ) , config( 'mail.childNode.port' ) ?config( 'mail.childNode.port' ): 22 );
```
或者
```php
 $sendMail = new MainController( config( 'mail.childNode.ip' ) , config( 'mail.childNode.port' ) );
```
不过可能在其他地方也有这么写，可能都要修改一下，所以还是推荐升级 `php` 版本到 `7`

[`CentOS7.2` 下的 `yum` 安装 `php7` 教程 ](http://www.centoscn.com/image-text/install/2015/1222/6560.html)
